id: IC7EDB1DC
legacy_id: P009521
ocr_import_info:
  bdrc_scan_id: W1KG20639
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T16:11:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T06:42:01.311950+00:00'
last_modified: 2022-08-27 14:42:57.517383
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG20639
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG20639
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆུ་ཆེན་ལོ་རྒྱུས་དཔྱད་ཡིག
statistics:
  ocr_word_mean_confidence_index: 0.8665211605615653
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG20758:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG20758
      total_pages: 416
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG20758.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8861570302644848
    legacy_id: v001
  I1KG20759:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG20759
      total_pages: 302
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG20759.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8419965183715412
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
