id: IC7EDB1DC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:13:24+00:00'
last_modified: '2022-06-08T11:37:20.428641+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG20639
  title: ཆུ་ཆེན་ལོ་རྒྱུས་དཔྱད་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E7AA:
      image_group_id: I1KG20758
      title: ''
      total_pages: 416
      order: 1
      base_file: E7AA.txt
    CD47:
      image_group_id: I1KG20759
      title: ''
      total_pages: 302
      order: 2
      base_file: CD47.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
